build:
    ../node_modules/.bin/wasm-pack build --target web --out-dir pkg --dev

build-prod:
    ../node_modules/.bin/wasm-pack build --target web --out-dir pkg --release

example: build
    cd example && ../../node_modules/.bin/vite dev

test: build
    ../node_modules/.bin/vitest

test-only testName: build
    ../node_modules/.bin/vitest -t {{testName}}
